Repository Team-Enigma23/social-media-integration-feed-project, pull requests merged in 2023-10, with the labels that each got.

#2 docs: Add README.MD
  README.MD
Labels: documentation

#12 Feat #11 : 게시글 디렉토리 구조 수정
  src/main/java/com/example/socialmediafeed/domain/content/entity/Content.java
  src/main/java/com/example/socialmediafeed/domain/post/controller/PostController.java
  src/main/java/com/example/socialmediafeed/domain/post/entity/Post.java
  src/main/java/com/example/socialmediafeed/domain/post/entity/TypeStatus.java
  src/main/java/com/example/socialmediafeed/domain/post/repository/PostRepository.java
  src/main/java/com/example/socialmediafeed/domain/post/service/PostService.java
  src/main/java/com/example/socialmediafeed/domain/posthashtag/entity/PostHashtag.java
Labels: enhancement

#16 인증에 사용할 컬럼 추가
  src/main/java/com/example/socialmediafeed/domain/user/entitiy/IsActive.java
  src/main/java/com/example/socialmediafeed/domain/user/entitiy/User.java
Labels: enhancement

#19 회원가입 API 구현 완료
  build.gradle
  src/main/java/com/example/socialmediafeed/domain/hashtag/entity/Hashtag.java
  src/main/java/com/example/socialmediafeed/domain/hashtag/repository/HashtagRepository.java
  src/main/java/com/example/socialmediafeed/domain/post/entity/TypeStatus.java
  src/main/java/com/example/socialmediafeed/domain/posthashtag/entity/PostHashtag.java
  src/main/java/com/example/socialmediafeed/domain/user/controller/UserApiController.java
  src/main/java/com/example/socialmediafeed/domain/user/dto/SignupReqDto.java
  src/main/java/com/example/socialmediafeed/domain/user/dto/SignupResDto.java
  src/main/java/com/example/socialmediafeed/domain/user/entitiy/User.java
  src/main/java/com/example/socialmediafeed/domain/user/repository/HashtagRepoForUser.java
  src/main/java/com/example/socialmediafeed/domain/user/repository/UserRepository.java
  src/main/java/com/example/socialmediafeed/domain/user/service/UserActService.java
  src/main/java/com/example/socialmediafeed/domain/user/service/UserSignupService.java
  src/main/java/com/example/socialmediafeed/global/config/SecurityConfig.java
  src/test/java/com/example/socialmediafeed/IntegrationTest.java
  src/test/java/com/example/socialmediafeed/domain/user/controller/UserApiControllerTest.java
Labels: enhancement

#21 User 가입 승인 API
  src/main/java/com/example/socialmediafeed/domain/user/controller/UserApiController.java
  src/main/java/com/example/socialmediafeed/domain/user/dto/ApprovalReqDto.java
  src/main/java/com/example/socialmediafeed/domain/user/entitiy/User.java
  src/main/java/com/example/socialmediafeed/domain/user/service/UserApprovalService.java
  src/main/java/com/example/socialmediafeed/domain/user/service/UserSignupService.java
Labels: enhancement

#24 API 기능 오류 수정
  src/main/java/com/example/socialmediafeed/domain/user/controller/UserApiController.java
  src/main/java/com/example/socialmediafeed/domain/user/dto/SignupReqDto.java
  src/main/java/com/example/socialmediafeed/domain/user/service/UserSignupService.java
  src/main/java/com/example/socialmediafeed/global/config/SecurityConfig.java
Labels: enhancement

#28 Fix #27: Post 오류 수정
  src/main/java/com/example/socialmediafeed/SocialMediaFeedApplication.java
  src/main/java/com/example/socialmediafeed/domain/post/entity/Post.java
  src/main/java/com/example/socialmediafeed/domain/post/service/PostService.java
  src/main/java/com/example/socialmediafeed/domain/posthashtag/entity/PostHashtag.java
  src/main/resources/application.yml
Labels: bug

#30 Feat: Jwt 로그인 진행 중
  build.gradle
  src/main/java/com/example/socialmediafeed/domain/user/controller/UserApiController.java
  src/main/java/com/example/socialmediafeed/domain/user/dto/SignInReqDto.java
  src/main/java/com/example/socialmediafeed/domain/user/repository/UserRepository.java
  src/main/java/com/example/socialmediafeed/domain/user/service/CustomUserDetails.java
  src/main/java/com/example/socialmediafeed/domain/user/service/UserSignInService.java
  src/main/java/com/example/socialmediafeed/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: enhancement

#26 Feat #25: 통계 기초 Controller 및 Service 생성
  src/main/java/com/example/socialmediafeed/domain/statistics/controller/StatisticsController.java
  src/main/java/com/example/socialmediafeed/domain/statistics/dto/StatisticsResponseDto.java
  src/main/java/com/example/socialmediafeed/domain/statistics/service/StatisticsService.java
Labels: enhancement

#33 Test #32: Approval test 코드 작성
  src/main/java/com/example/socialmediafeed/domain/user/dto/ApprovalReqDto.java
  src/test/java/com/example/socialmediafeed/domain/HashtagSetup.java
  src/test/java/com/example/socialmediafeed/domain/UserSetup.java
  src/test/java/com/example/socialmediafeed/domain/user/controller/UserApiControllerTest.java
Labels: test

#37 Feat #25: QueryDsl 환경 설정
  build.gradle
  src/main/java/com/example/socialmediafeed/domain/statistics/controller/StatisticsController.java
  src/main/java/com/example/socialmediafeed/global/config/QuerydslConfig.java
Labels: enhancement

#35 Feat #34 : 게시물 목록(API) 작성
  src/main/java/com/example/socialmediafeed/domain/post/controller/PostController.java
  src/main/java/com/example/socialmediafeed/domain/post/repository/PostRepository.java
  src/main/java/com/example/socialmediafeed/domain/post/service/DummyDataLoader.java
  src/main/java/com/example/socialmediafeed/domain/post/service/DummyDataService.java
  src/main/java/com/example/socialmediafeed/domain/post/service/PostService.java
  src/test/java/com/example/socialmediafeed/domain/post/controller/PostControllerTest.java
Labels: enhancement

#48 Feat #41 : 게시물 상세(API) 작성
  src/main/java/com/example/socialmediafeed/domain/post/controller/PostController.java
  src/main/java/com/example/socialmediafeed/domain/post/entity/Post.java
  src/main/java/com/example/socialmediafeed/domain/post/service/PostReadService.java
  src/test/java/com/example/socialmediafeed/domain/post/controller/PostControllerTest.java
Labels: enhancement

#45 Feat #25 : Statistics API 구현
  .gitignore
  src/main/java/com/example/socialmediafeed/domain/statistics/controller/StatisticsController.java
  src/main/java/com/example/socialmediafeed/domain/statistics/dto/StatisticsResponseDto.java
  src/main/java/com/example/socialmediafeed/domain/statistics/repository/StatisticsRepository.java
  src/main/java/com/example/socialmediafeed/domain/statistics/repository/StatisticsRepositoryCustom.java
  src/main/java/com/example/socialmediafeed/domain/statistics/repository/StatisticsRepositoryImpl.java
  src/main/java/com/example/socialmediafeed/domain/statistics/service/StatisticsService.java
  src/main/java/com/example/socialmediafeed/global/error/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: enhancement

#46 docs #40: README.MD 문서 작업 진행 중
  README.MD
  src/main/resources/static/img/table.png
  src/main/resources/static/img/test.png
Labels: documentation

#42 Feat #29 : JWT 로그인 구현
  build.gradle
  src/main/java/com/example/socialmediafeed/domain/jwtoken/controller/TokenApiController.java
  src/main/java/com/example/socialmediafeed/domain/jwtoken/dto/CreateAccessTokenReqDto.java
  src/main/java/com/example/socialmediafeed/domain/jwtoken/dto/CreateAccessTokenResDto.java
  src/main/java/com/example/socialmediafeed/domain/jwtoken/entity/RefreshToken.java
  src/main/java/com/example/socialmediafeed/domain/jwtoken/repository/RefreshTokenRepository.java
  src/main/java/com/example/socialmediafeed/domain/jwtoken/service/RefreshTokenService.java
  src/main/java/com/example/socialmediafeed/domain/jwtoken/service/TokenService.java
  src/main/java/com/example/socialmediafeed/domain/user/controller/UserApiController.java
  src/main/java/com/example/socialmediafeed/domain/user/dto/SignInReqDto.java
  src/main/java/com/example/socialmediafeed/domain/user/dto/SignupReqDto.java
  src/main/java/com/example/socialmediafeed/domain/user/dto/SignupResDto.java
  src/main/java/com/example/socialmediafeed/domain/user/entitiy/Authority.java
  src/main/java/com/example/socialmediafeed/domain/user/entitiy/User.java
  src/main/java/com/example/socialmediafeed/domain/user/repository/UserRepository.java
  src/main/java/com/example/socialmediafeed/domain/user/service/UserService.java
  src/main/java/com/example/socialmediafeed/domain/user/service/UserSignInService.java
  src/main/java/com/example/socialmediafeed/global/config/SecurityConfig.java
  src/main/java/com/example/socialmediafeed/global/config/WebSecurityConfig.java
  src/main/java/com/example/socialmediafeed/global/config/jwt/TokenAuthenticationFilter.java
  src/main/java/com/example/socialmediafeed/global/config/jwt/TokenProvider.java
  src/main/resources/application.yml
  src/test/java/com/example/socialmediafeed/domain/jwtoken/controller/TokenApiControllerTest.java
  src/test/java/com/example/socialmediafeed/domain/setup/UserSetup.java
  src/test/java/com/example/socialmediafeed/domain/user/controller/UserApiControllerTest.java
  src/test/java/com/example/socialmediafeed/global/config/jwt/JwtFactory.java
  src/test/java/com/example/socialmediafeed/global/config/jwt/TokenProviderTest.java
Labels: enhancement

#51 이메일 전송 기능 구현
  build.gradle
  src/main/java/com/example/socialmediafeed/domain/user/controller/UserController.java
  src/main/java/com/example/socialmediafeed/domain/user/dto/EmailMessage.java
  src/main/java/com/example/socialmediafeed/domain/user/service/EmailService.java
  src/main/java/com/example/socialmediafeed/domain/user/service/UserSignupService.java
  src/main/resources/application.yml
  src/main/resources/templates/mail/email.html
  src/test/java/com/example/socialmediafeed/domain/hashtag/controller/HashtagControllerTest.java
Labels: enhancement

#52 Feat #47 : 게시물 좋아요(API) 작성
  src/main/java/com/example/socialmediafeed/domain/post/controller/PostController.java
  src/main/java/com/example/socialmediafeed/domain/post/entity/Post.java
  src/main/java/com/example/socialmediafeed/domain/post/service/PostInteractionService.java
  src/main/java/com/example/socialmediafeed/domain/post/service/PostReadService.java
  src/main/java/com/example/socialmediafeed/domain/post/service/SnsFeedService.java
  src/main/java/com/example/socialmediafeed/domain/post/service/SnsFeedServiceImpl.java
  src/test/java/com/example/socialmediafeed/domain/post/controller/PostControllerTest.java
Labels: enhancement

#54 Feat #53 : 게시물 공유(API) 작성
  src/main/java/com/example/socialmediafeed/domain/post/controller/PostController.java
  src/main/java/com/example/socialmediafeed/domain/post/entity/Post.java
  src/main/java/com/example/socialmediafeed/domain/post/service/PostInteractionService.java
  src/test/java/com/example/socialmediafeed/domain/post/controller/PostControllerTest.java
Labels: enhancement

#55 Gabang2/statistics api
  src/main/java/com/example/socialmediafeed/domain/post/service/DummyDataService.java
  src/main/java/com/example/socialmediafeed/domain/statistics/controller/StatisticsController.java
  src/main/java/com/example/socialmediafeed/domain/user/service/UserService.java
Labels: enhancement
